services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - TZ=Europe/London
      - LOG_FILE=true
    volumes:
      - ./:/config
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - SERVER_HOST=${SERVER_HOST}
    volumes:
      - ./nginx:/etc/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:80/health || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 1
      start_period: 15s

  certbot:
    image: certbot/dns-cloudflare
    volumes:
      - ./certbot/cloudflare.ini:/root/cloudflare.ini:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
