services:
  duckdns:
    image: ghcr.io/linuxserver/duckdns
    container_name: duckdns
    environment:
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - TZ=Europe/London
      - LOG_FILE=true
    volumes:
      - ./:/config
    restart: unless-stopped
